######################################################################
##
## Filename: procesador_tb.udo
## Created on: Wed Nov 04 12:00:43 Hora estándar romance 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
